name: Build and Push Vast Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set lowercase username
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

      - name: Log in to GHCR
        uses: docker/login-action@v5
        with:
          registry: ${{ env.REGISTRY }}
          username: ${ REPO_LOWER }
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./vast.ai-blender
          push: true
          tags: |
            ghcr.io/${ REPO_LOWER }/vast-gpu-box:latest
