name: Build and Push Vast Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # 1. Free up disk space (Solves the "No space left" error)
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
        #  docker system prune -af

      # 2. MANDATORY: Create a BuildKit builder (Solves your Error)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container

      # -----------------------------
      # Lowercase GHCR owner
      # -----------------------------
      - name: Set lowercase username
        id: vars
        run: |
          echo "REPO_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo ${REPO_LOWER}

        # run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${REPO_LOWER}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./vast.ai-blender
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.REPO_LOWER }}/vast-gpu-box:latest
          #  ghcr.io/${{ github.repository_owner }}/vast-gpu-box:latest
          # This magic line enables the remote cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
