name: Build and Push Vast Image

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      # -----------------------------
      # Lowercase GHCR owner
      # -----------------------------
      - name: Set lowercase username
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
          echo ${REPO_LOWER}

        # run: echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${REPO_LOWER}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./vast.ai-blender
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.REPO_LOWER }}/vast-gpu-box:latest
